version: '3'

services:
  python: &python
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.7-alpine
  celery_worker:
    <<: *python
    command: celery -A resize_backend worker --loglevel=info
    ports: []
    depends_on:
      - rabbitmq
